import { defineConfig } from 'vite'
import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'
import basicSsl from '@vitejs/plugin-basic-ssl'

import { cloudflare } from "@cloudflare/vite-plugin";

export default defineConfig({
  // Serve the dev server over HTTPS (self-signed cert generated by basicSsl).
  // The browser will show a one-time "not secure" warning you can accept.
  server: {
    https: true,
    port: 5173,
    strictPort: true, // fail instead of drifting to 5174, so auth redirect URLs stay stable
  },
  plugins: [basicSsl(), react(), tailwindcss(), VitePWA({
    registerType: 'autoUpdate',
    includeAssets: ['default.svg', 'active.svg', 'active-spinning.svg', 'stop.svg'],
    manifest: {
      name: 'Kronos',
      short_name: 'Kronos',
      description: 'Time tracking and productivity app',
      theme_color: '#2D527C',
      background_color: '#ffffff',
      display: 'standalone',
      start_url: '/',
      icons: [
        { src: 'kronos-64.png', sizes: '64x64', type: 'image/png' },
        { src: 'kronos-192.png', sizes: '192x192', type: 'image/png' },
        { src: 'kronos-512.png', sizes: '512x512', type: 'image/png' },
        { src: 'kronos-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
      ],
    },
    devOptions: {
      enabled: true,
    },
    workbox: {
      maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
      globPatterns: ['**/*.{js,css,html,svg,ico,woff,woff2}'],
      runtimeCaching: [
        {
          urlPattern: /^https:\/\/fonts\.(googleapis|gstatic)\.com\/.*/i,
          handler: 'CacheFirst',
          options: {
            cacheName: 'google-fonts-cache',
            expiration: { maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 365 },
            cacheableResponse: { statuses: [0, 200] },
          },
        },
      ],
    },
  }), cloudflare()],
})